#!/bin/bash
CHECKSUM="${CHECKSUM:-sha512sum}"

lookup=0
if [[ "$1" == "-l" ]]; then
	lookup=1
	shift
fi

dir="$1"
key="$2"

if [[ -z "$dir" || ! -d "$dir" ]]; then
	echo "usage: $0 [-l] dir [key]" 1>&2
	exit 1
fi

sum="$(echo -n "$key" | "$CHECKSUM" | cut -f 1 -d ' ')"
if [[ ! -d "$dir/$sum" ]]; then
	if [[ "$lookup" -eq 1 ]]; then
		exit 1
	fi
	mkdir -p "$dir/$sum"
fi

while read -r entry; do
	if [[ "$(cat "$entry/key")" == "$key" ]]; then
		echo "$entry"
		exit 0
	fi
done < <(find "$dir/$sum" -mindepth 1 -maxdepth 1)

if [[ "$lookup" -eq 1 ]]; then
	exit 1
fi

entry="$(mktemp -p "$dir/$sum" -d XXXXXXXX)"
echo -n "$key" > "$entry/key"
echo "$entry"
